{{- if and (not .Values.mongodb.enabled) (not .Values.externalMongoDB.auth.existingSecret) (eq (include "mychart.mongodb.auth.enabled" .) "true") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.mongodb.secretName" . }}
data:
  {{- if and (include "mychart.mongodb.usernames" .) (include "mychart.mongodb.passwords" .) }}
  mongodb-passwords: {{ include "mychart.mongodb.passwords" . | b64enc }}
  {{- end }}
  mongodb-root-password: {{ .Values.externalMongoDB.auth.rootPassword | default (randAlpha 32) | b64enc }}
{{- end }}
