---
apiVersion: v2
name: mariadb-and-postgresql-dependency
type: library
version: 1.0.0
dependencies:
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.4.0
    condition: mariadb.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.12.0
    condition: postgresql.enabled
maintainers:
  - name: christianknell
    email: christian@knell.it
    url: https://knell.it
