---
apiVersion: v2
name: mongodb-dependency
type: library
version: 1.0.0
dependencies:
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 13.6.3
    condition: mongodb.enabled
maintainers:
  - name: christianknell
    email: christian@knell.it
    url: https://knell.it
