{{- if and (not .Values.memcached.enabled) (not .Values.externalMemcached.auth.existingSecret) (eq (include "mychart.memcached.auth.enabled" .) "true") (.Values.externalMemcached.auth.password) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.memcached.secretName" . }}
data:
  {{- include "mychart.memcached.userPasswordKey" . | nindent 2 }}: {{ .Values.externalMemcached.auth.password | b64enc }}
{{- end }}
