---
apiVersion: v2
name: postgresql-and-mariadb-dependency
type: application
version: 1.0.0
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.2
    condition: postgresql.enabled
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.4.0
    condition: mariadb.enabled
maintainers:
  - name: christianknell
    email: christian@knell.it
    url: https://knell.it
