{{- if and (not .Values.mysql.enabled) (not .Values.externalMysql.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.mysql.secretName" . }}
data:
  {{- include "mychart.mysql.userPasswordKey" . | nindent 2 }}: {{ .Values.externalMysql.auth.password | b64enc }}
{{- end }}
