---
postgresql:
  enabled: true
  auth:
    database: mychart
    password: mychart
    username: mychart

externalPostgresql:
  auth:
    database: mychart
    existingSecret: ""
    password: mychart
    username: mychart
    userPasswordKey: ""
  hostname: ""
  port: 5432
