{{- if and (not .Values.mariadb.enabled) (not .Values.externalMariadb.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.mariadb.secretName" . }}
data:
  {{- include "mychart.mariadb.userPasswordKey" . | nindent 2 }}: {{ .Values.externalMariadb.auth.password | b64enc }}
{{- end }}
