---
mariadb:
  # -- enable MariaDB™ subchart from Bitnami
  enabled: true
  auth:
    # -- Name for a custom database to create
    database: mychart
    # -- Name of existing secret to use for MariaDB credentials
    existingSecret: ""
    # -- Password for the custom user to create. Ignored if mariadb.auth.existingSecret is provided
    password: mychart
    # -- Name for a custom user to create
    username: mychart

externalMariadb:
  auth:
    # -- Name of the database to use
    database: mychart
    # -- Name of existing secret to use for MariaDB credentials
    existingSecret: ""
    # -- Password to use
    password: mychart
    # -- Name of the user to use
    username: mychart
    # -- Key in the secret containing the password
    userPasswordKey: ""
  # -- Hostname of the MariaDB database
  hostname: ""
  # -- Port used to connect to MariaDB database
  port: 3306
