{{- if and (not .Values.mysql.enabled) (not .Values.postgresql.enabled) (not .Values.externalDatabase.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.database.secretName" . }}
data:
  {{- include "mychart.database.userPasswordKey" . | nindent 2 }}: {{ .Values.externalDatabase.auth.password | b64enc }}
{{- end }}
