apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            # Database Settings
            - name: DB_HOST
              value: {{ include "mychart.postgresql.hostname" . | quote }}
            - name: DB_PORT
              value: {{ include "mychart.postgresql.port" . | quote }}
            - name: DB_NAME
              value: {{ include "mychart.postgresql.database" . | quote }}
            - name: DB_USER
              value: {{ include "mychart.postgresql.username" . | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mychart.postgresql.secretName" . | quote }}
                  key: {{ include "mychart.postgresql.userPasswordKey" . | quote }}
