---
redis:
  enabled: true
  auth:
    enabled: true
    password: mychart

externalRedis:
  auth:
    enabled: true
    existingSecret: ""
    password: ""
    userPasswordKey: ""
  hostname: ""
  port: 6379
