---
redis:
  # -- enable Redis™ subchart from Bitnami
  enabled: true
  auth:
    # -- Enable password authentication
    enabled: true
    # -- Redis™ password
    password: mychart

externalRedis:
  auth:
    # -- if authentication should be used with external Redis™
    enabled: true
    # -- Name of existing secret to use for Redis™ credentials
    existingSecret: ""
    # -- Password to use
    password: ""
    # -- Key in the secret containing the password
    userPasswordKey: ""
  # -- Hostname of Redis™
  hostname: ""
  # -- Port used to connect to Redis
  port: 6379
