---
apiVersion: v2
name: mysql-and-mariadb-dependency
type: library
version: 1.0.0
dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 9.4.4
    condition: mysql.enabled
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.4.0
    condition: mariadb.enabled
maintainers:
  - name: christianknell
    email: christian@knell.it
    url: https://knell.it
