apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            # Database Settings
            - name: DB_TYPE
              value: {{ include "mychart.database.type" . | quote }}
            - name: DB_HOST
              value: {{ include "mychart.database.hostname" . | quote }}
            - name: DB_PORT
              value: {{ include "mychart.database.port" . | quote }}
            - name: DB_NAME
              value: {{ include "mychart.database.database" . | quote }}
            - name: DB_USER
              value: {{ include "mychart.database.username" . | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mychart.database.secretName" . | quote }}
                  key: {{ include "mychart.database.userPasswordKey" . | quote }}
